// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['service']['HotKey']['Close']();
}

export function Startup(arg1) {
  return window['go']['service']['HotKey']['Startup'](arg1);
}

export function SyncFrontParse(arg1) {
  return window['go']['service']['HotKey']['SyncFrontParse'](arg1);
}

export function SyncFrontStart(arg1) {
  return window['go']['service']['HotKey']['SyncFrontStart'](arg1);
}

export function SyncFrontStop(arg1) {
  return window['go']['service']['HotKey']['SyncFrontStop'](arg1);
}
