// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';

export function Close():Promise<void>;

export function Startup(arg1:service.Keyboard):Promise<void>;

export function SyncFrontParse(arg1:number):Promise<string>;

export function SyncFrontStart(arg1:number):Promise<string>;

export function SyncFrontStop(arg1:number):Promise<string>;
