// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DllImport() {
  return window['go']['service']['Keyboard']['DllImport']();
}

export function ParseKeyThread() {
  return window['go']['service']['Keyboard']['ParseKeyThread']();
}

export function StartKeyThread() {
  return window['go']['service']['Keyboard']['StartKeyThread']();
}

export function Startup(arg1, arg2) {
  return window['go']['service']['Keyboard']['Startup'](arg1, arg2);
}

export function StopKeyThread() {
  return window['go']['service']['Keyboard']['StopKeyThread']();
}

export function SyncFrontKey(arg1) {
  return window['go']['service']['Keyboard']['SyncFrontKey'](arg1);
}

export function SyncFrontModel(arg1) {
  return window['go']['service']['Keyboard']['SyncFrontModel'](arg1);
}

export function SyncFrontMs(arg1) {
  return window['go']['service']['Keyboard']['SyncFrontMs'](arg1);
}

export function SyncFrontVoice(arg1) {
  return window['go']['service']['Keyboard']['SyncFrontVoice'](arg1);
}

export function ThreadExec(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['service']['Keyboard']['ThreadExec'](arg1, arg2, arg3, arg4, arg5);
}
