// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DllImport() {
  return window['go']['service']['Keyboard']['DllImport']();
}

export function ExportPlans(arg1) {
  return window['go']['service']['Keyboard']['ExportPlans'](arg1);
}

export function ImportPlans() {
  return window['go']['service']['Keyboard']['ImportPlans']();
}

export function ParseKeyThread() {
  return window['go']['service']['Keyboard']['ParseKeyThread']();
}

export function ParseStartThread() {
  return window['go']['service']['Keyboard']['ParseStartThread']();
}

export function ParseStopThread() {
  return window['go']['service']['Keyboard']['ParseStopThread']();
}

export function StartKeyThread() {
  return window['go']['service']['Keyboard']['StartKeyThread']();
}

export function Startup(arg1, arg2) {
  return window['go']['service']['Keyboard']['Startup'](arg1, arg2);
}

export function StopKeyThread() {
  return window['go']['service']['Keyboard']['StopKeyThread']();
}

export function SyncDisabled(arg1) {
  return window['go']['service']['Keyboard']['SyncDisabled'](arg1);
}

export function SyncFrontKey(arg1) {
  return window['go']['service']['Keyboard']['SyncFrontKey'](arg1);
}

export function SyncFrontModel(arg1) {
  return window['go']['service']['Keyboard']['SyncFrontModel'](arg1);
}

export function SyncFrontMs(arg1) {
  return window['go']['service']['Keyboard']['SyncFrontMs'](arg1);
}

export function SyncParseType(arg1) {
  return window['go']['service']['Keyboard']['SyncParseType'](arg1);
}

export function ThreadExec(arg1, arg2, arg3, arg4) {
  return window['go']['service']['Keyboard']['ThreadExec'](arg1, arg2, arg3, arg4);
}
