// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SelectMusic() {
  return window['go']['service']['Music']['SelectMusic']();
}

export function Startup(arg1) {
  return window['go']['service']['Music']['Startup'](arg1);
}
